services:
  - type: web
    name: voice-support-bot
    env: python
    region: frankfurt
    buildCommand: "pip install -r requirements.txt"
    startCommand: "python app.py"
    envVars:
      - key: BOT_TOKEN
        sync: false
      - key: YANDEX_API_KEY
        sync: false
      - key: FOLDER_ID
        sync: false
